# pyfiles/input_variables.py
"""
Human-readable labels for EnergyPLAN input file parameters.
Keys are the exact parameter names used in the .txt input file.
Fuel indices: [1]=Coal [2]=Oil [3]=Natural gas [4]=Biomass
              [5]=H2/Biofuel [6]=Biogas [7]=Bio-oil [8]=Waste [9]=Various [10/11/12]=extra
"""

labels = {

    # ── 1. System settings ──────────────────────────────────────────────────────
    'EnergyUnit':                       'Energy unit',
    'CapacityUnit':                     'Capacity unit',
    'MonetaryUnit':                     'Monetary unit',
    'EmissionUnit':                     'Emission unit',
    'input_regulation':                 'Technical regulation strategy (1–5)',
    'input_marketmodel':                'Electricity market model',
    'input_Interest':                   'Interest rate (%)',
    'input_CO2_price':                  'CO2 price (EUR/t)',
    'input_Maintain_price':             'Maintain price signal',
    'ThermalStorageDays':               'Thermal storage regulation days',

    # ── 2. Demand ────────────────────────────────────────────────────────────────
    'Input_el_demand_Twh':              'Electricity demand (TWh)',
    'Input_El_demand_elec_heating_share': 'Electric heating share of electricity demand',
    'Input_El_demand_cooling_share':    'Cooling share of electricity demand (TWh)',
    'input_dh_demand_TWh':             'District heating demand (TWh)',
    'Input_add_el_TWh':                'Additional electricity demand (TWh)',
    'input_Heatdemand_PerHouse':       'Heat demand per house (kWh)',
    'input_dh_ann_gr1':                'DH annual demand group 1 (TWh)',
    'input_dh_ann_gr2':                'DH annual demand group 2 (TWh)',
    'input_dh_ann_gr3':                'DH annual demand group 3 (TWh)',
    'input_dh_ann_loss_gr1':           'DH distribution loss group 1',
    'input_dh_ann_loss_gr2':           'DH distribution loss group 2',
    'input_dh_ann_loss_gr3':           'DH distribution loss group 3',

    # ── 3. RES capacities & factors ─────────────────────────────────────────────
    'NameRES1':                        'RES1 name',
    'NameRES2':                        'RES2 name',
    'NameRES3':                        'RES3 name',
    'NameRES4':                        'RES4 name',
    'NameRES5':                        'RES5 name',
    'NameRES6':                        'RES6 name',
    'NameRES7':                        'RES7 name',
    'input_RES1_capacity':             'RES1 capacity (MW) — Onshore wind',
    'input_RES2_capacity':             'RES2 capacity (MW) — Offshore wind',
    'input_RES3_capacity':             'RES3 capacity (MW) — Solar PV',
    'input_RES4_capacity':             'RES4 capacity (MW) — River hydro',
    'input_RES5_capacity':             'RES5 capacity (MW) — Tidal',
    'input_RES6_capacity':             'RES6 capacity (MW) — Wave',
    'input_RES7_capacity':             'RES7 capacity (MW) — CSP',
    'input_RES1_factor':               'RES1 capacity factor',
    'input_RES2_factor':               'RES2 capacity factor',
    'input_RES3_factor':               'RES3 capacity factor',
    'input_RES4_factor':               'RES4 capacity factor',
    'input_RES5_factor':               'RES5 capacity factor',
    'input_RES6_factor':               'RES6 capacity factor',
    'input_RES7_factor':               'RES7 capacity factor',
    'input_RES1_stab_share':           'RES1 grid stabilisation share',
    'input_RES2_stab_share':           'RES2 grid stabilisation share',
    'input_RES3_stab_share':           'RES3 grid stabilisation share',
    'input_RES4_stab_share':           'RES4 grid stabilisation share',
    'input_RES5_stab_share':           'RES5 grid stabilisation share',
    'input_RES6_stab_share':           'RES6 grid stabilisation share',
    'input_RES7_stab_share':           'RES7 grid stabilisation share',

    # ── 4. Flexible electricity demand ───────────────────────────────────────────
    'input_flexible_day_TWh':          'Flexible demand — daily shift (TWh)',
    'input_flexible_week_TWh':         'Flexible demand — weekly shift (TWh)',
    'input_flexible_4weeks_TWh':       'Flexible demand — 4-week shift (TWh)',
    'input_flexible_day_max':          'Flexible demand — daily max capacity (MW)',
    'input_flexible_week_max':         'Flexible demand — weekly max capacity (MW)',
    'input_flexible_4weeks_max':       'Flexible demand — 4-week max capacity (MW)',
    'input_AddExport_TWh':             'Fixed additional export (TWh)',

    # ── 5. Solar heat & CSHP ─────────────────────────────────────────────────────
    'input_solar_ann_gr1':             'Solar heat group 1 (TWh)',
    'input_solar_ann_gr2':             'Solar heat group 2 (TWh)',
    'input_solar_ann_gr3':             'Solar heat group 3 (TWh)',
    'input_solar_storage_gr1':         'Solar storage group 1 (GWh)',
    'input_solar_storage_gr2':         'Solar storage group 2 (GWh)',
    'input_solar_storage_gr3':         'Solar storage group 3 (GWh)',
    'input_solar_share_gr1':           'Solar share group 1',
    'input_solar_share_gr2':           'Solar share group 2',
    'input_solar_share_gr3':           'Solar share group 3',
    'input_solar_loss_gr1':            'Solar storage loss group 1',
    'input_solar_loss_gr2':            'Solar storage loss group 2',
    'input_solar_loss_gr3':            'Solar storage loss group 3',
    'input_cshp_th_gr1':               'CSHP thermal output group 1 (TWh)',
    'input_cshp_th_gr2':               'CSHP thermal output group 2 (TWh)',
    'input_cshp_th_gr3':               'CSHP thermal output group 3 (TWh)',
    'input_cshp_el_gr1':               'CSHP electricity output group 1 (TWh)',
    'input_cshp_el_gr2':               'CSHP electricity output group 2 (TWh)',
    'input_cshp_el_gr3':               'CSHP electricity output group 3 (TWh)',
    'input_cshp_th_own_gr1':           'CSHP own heat group 1',
    'input_cshp_th_own_gr2':           'CSHP own heat group 2',
    'input_cshp_th_own_gr3':           'CSHP own heat group 3',

    # ── 6. CHP groups 2 & 3 ──────────────────────────────────────────────────────
    'input_cap_chp2_el':               'CHP group 2 electric capacity (MW)',
    'input_cap_chp2_thermal':          'CHP group 2 thermal capacity (MW)',
    'input_eff_chp2_el':               'CHP group 2 electric efficiency',
    'input_eff_chp2_th':               'CHP group 2 thermal efficiency',
    'input_cap_chp3_el':               'CHP group 3 electric capacity (MW)',
    'input_cap_chp3_thermal':          'CHP group 3 thermal capacity (MW)',
    'input_eff_chp3_el':               'CHP group 3 electric efficiency',
    'input_eff_chp3_th':               'CHP group 3 thermal efficiency',
    'input_chpgr3_cap_minimum':        'CHP group 3 minimum capacity',
    'input_pp_cap_minimum':            'Power plant minimum capacity',
    'Input_chp_thermal_cap_button':    'CHP thermal capacity mode (Auto/Manual)',

    # ── 7. Heat pumps ────────────────────────────────────────────────────────────
    'input_cap_hp2_el':                'HP group 2 capacity (MW)',
    'input_eff_hp2_cop':               'HP group 2 COP',
    'input_cap_hp3_el':                'HP group 3 capacity (MW)',
    'input_eff_hp3_cop':               'HP group 3 COP',
    'input_hp_maxload':                'HP max load factor (group 2)',
    'input_hp_maxload2':               'HP max load factor (group 3)',
    'Input_HeatPumpRegulation':        'Heat pump regulation mode',

    # ── 8. Boilers & electric heating ────────────────────────────────────────────
    'input_cap_boiler2_th':            'Boiler group 2 capacity (MW)',
    'input_eff_boiler2_th':            'Boiler group 2 efficiency',
    'input_cap_boiler3_th':            'Boiler group 3 capacity (MW)',
    'input_eff_boiler3_th':            'Boiler group 3 efficiency',
    'input_FixedBoiler2':              'Fixed boiler share group 2',
    'input_FixedBoiler3':              'Fixed boiler share group 3',
    'input_eh2':                       'Electric heating capacity group 2 (MW)',
    'input_eh3':                       'Electric heating capacity group 3 (MW)',
    'Input_Inv_EHgr2gr3':             'Electric heating investment cost (MEUR/MW)',
    'Input_Period_EHgr2gr3':          'Electric heating lifetime (years)',
    'Input_FOM_EHgr2gr3':             'Electric heating fixed O&M (%)',

    # ── 9. Power plants ──────────────────────────────────────────────────────────
    'input_cap_pp_el':                 'Power plant (PP) capacity (MW)',
    'input_eff_pp_el':                 'Power plant efficiency',
    'input_cap_pp2_el':                'Peak load plant (PP2) capacity (MW)',
    'input_eff_pp2_el':                'Peak load plant efficiency',
    'input_eff_dhp_th':                'District heating plant thermal efficiency',
    'Input_IncludeEB2':                'Include electric boiler group 2',
    'Input_IncludeEB3':                'Include electric boiler group 3',

    # ── 10. Nuclear ───────────────────────────────────────────────────────────────
    'input_nuclear_cap':               'Nuclear capacity (MW)',
    'input_nuclear_eff':               'Nuclear efficiency',
    'input_Nuclear_factor':            'Nuclear capacity factor',
    'input_Nuclear_partload':          'Nuclear minimum partload',

    # ── 11. Hydro ─────────────────────────────────────────────────────────────────
    'input_hydro_cap':                 'Hydro capacity (MW)',
    'input_hydro_eff':                 'Hydro efficiency',
    'input_hydro_watersupply':         'Hydro water supply (TWh)',
    'input_hydro_storage':             'Hydro reservoir storage (TWh)',
    'input_hydro_pump_cap':            'Hydro pump capacity (MW)',
    'input_hydro_pump_eff':            'Hydro pump efficiency',
    'input_HydroPowerStorageYearBegin': 'Hydro storage level at year start',
    'input_HydroPowerStorageYearEnd':  'Hydro storage level at year end',
    'input_HydroPowerContentButton':   'Hydro storage content mode',

    # ── 12. Geothermal ────────────────────────────────────────────────────────────
    'input_geo_th_gr1':                'Geothermal heat group 1 (TWh)',
    'input_geo_th_gr2':                'Geothermal heat group 2 (TWh)',
    'input_geo_th_gr3':                'Geothermal heat group 3 (TWh)',
    'input_GeoPower_cap':              'Geothermal power capacity (MW)',
    'input_GeoPower_eff':              'Geothermal power efficiency',
    'input_GeoPower_factor':           'Geothermal capacity factor',
    'Input_Inv_geo_th':                'Geothermal heat investment (MEUR/MW)',
    'Input_FOM_geo_th':                'Geothermal heat fixed O&M (%)',
    'Input_Period_geo_th':             'Geothermal heat lifetime (years)',

    # ── 13. Industrial surplus heat ───────────────────────────────────────────────
    'input_ind_surplus_heat1':         'Industrial surplus heat group 1 (TWh)',
    'input_ind_surplus_heat2':         'Industrial surplus heat group 2 (TWh)',
    'input_ind_surplus_heat3':         'Industrial surplus heat group 3 (TWh)',
    'Input_Inv_ind_surplus_heat':      'Industrial surplus heat investment (MEUR/TWh)',
    'Input_FOM_ind_surplus_heat':      'Industrial surplus heat fixed O&M (%)',
    'Input_Period_ind_surplus_heat':   'Industrial surplus heat lifetime (years)',
    'Input_Inv_ind_CHP_elec':         'Industrial CHP electric investment (MEUR/MW)',
    'Input_Period_ind_CHP_elec':      'Industrial CHP electric lifetime (years)',
    'Input_FOM_ind_CHP_elec':         'Industrial CHP electric fixed O&M (%)',
    'Input_Inv_ind_CHP_heat':         'Industrial CHP heat investment (MEUR/MW)',
    'Input_Period_ind_CHP_heat':      'Industrial CHP heat lifetime (years)',
    'Input_FOM_ind_CHP_heat':         'Industrial CHP heat fixed O&M (%)',

    # ── 14. Waste ─────────────────────────────────────────────────────────────────
    'input_Waste1_Waste':              'Waste input group 1 (TWh)',
    'input_Waste2_Waste':              'Waste input group 2 (TWh)',
    'input_Waste3_Waste':              'Waste input group 3 (TWh)',
    'input_Waste1_Eff_th':             'Waste thermal efficiency group 1',
    'input_Waste2_Eff_th':             'Waste thermal efficiency group 2',
    'input_Waste3_Eff_th':             'Waste thermal efficiency group 3',
    'input_Waste1_Eff_el':             'Waste electric efficiency group 1',
    'input_Waste2_Eff_el':             'Waste electric efficiency group 2',
    'input_Waste3_Eff_el':             'Waste electric efficiency group 3',
    'input_Inv_Waste_CHP':             'Waste CHP investment (MEUR/MW)',
    'input_Period_Waste_CHP':          'Waste CHP lifetime (years)',
    'input_FOM_Waste_CHP':             'Waste CHP fixed O&M (%)',
    'input_stabilisation_share_waste': 'Waste grid stabilisation share',

    # ── 15. Electricity storage ───────────────────────────────────────────────────
    'input_storage_pump_cap':          'Electricity storage charging capacity (MW)',
    'input_cap_pump_el':               'Pump capacity (MW)',
    'input_eff_pump_el':               'Pump efficiency',
    'input_cap_turbine_el':            'Turbine capacity (MW)',
    'input_eff_turbine_el':            'Turbine efficiency',
    'input_cap_pump_el2':              'Pump 2 capacity (MW)',
    'input_eff_pump_el2':              'Pump 2 efficiency',
    'input_cap_turbine_el2':           'Turbine 2 capacity (MW)',
    'input_eff_turbine_el2':           'Turbine 2 efficiency',
    'input_storage_pump_cap2':         'Electricity storage 2 charging capacity (MW)',
    'input_CAES_fuel_ratio':           'CAES fuel ratio',
    'Input_CAES_hour_time':            'CAES regulation time (hours)',
    'input_ElecStorProfitMargin':      'Electricity storage profit margin',

    # ── 16. Thermal storage ───────────────────────────────────────────────────────
    'input_storage_gr2_cap':           'Thermal storage group 2 capacity (GWh)',
    'input_storage_gr3_cap':           'Thermal storage group 3 capacity (GWh)',
    'Input_ThermalStorageRegulationGr2': 'Thermal storage regulation mode group 2',
    'Input_ThermalStorageRegulationGr3': 'Thermal storage regulation mode group 3',

    # ── 17. Rock bed / steam storage ──────────────────────────────────────────────
    'input_cap_rock_el':               'Rock bed storage electric capacity (MW)',
    'input_cap_rock_steam':            'Rock bed steam output capacity (MW)',
    'input_rock_store_cap':            'Rock bed storage capacity (GWh)',
    'input_rock_store_loss':           'Rock bed storage loss rate',
    'share_rock_store':                'Rock bed storage share',
    'input_rock_steam_output_eff':     'Rock bed steam output efficiency',
    'input_rockbed_reg':               'Rock bed regulation mode',

    # ── 18. CSP ───────────────────────────────────────────────────────────────────
    'Input_CSP_Solar':                 'CSP solar input (TWh)',
    'Input_CSP_Storage_cap':           'CSP storage capacity (GWh)',
    'Input_CSP_Storage_eff':           'CSP storage efficiency',
    'Input_CSP_Power_cap':             'CSP power capacity (MW)',
    'Input_CSP_Power_eff':             'CSP power efficiency',
    'input_CSP_stab_share':            'CSP grid stabilisation share',

    # ── 19. Electrolysis & hydrogen ───────────────────────────────────────────────
    'input_cap_ELTtrans_el':           'Electrolysis (transport) capacity (MW)',
    'input_eff_ELTtrans_fuel':         'Electrolysis (transport) fuel efficiency',
    'input_eff_ELTCO2_fuel':           'Electrolysis (CO2) fuel efficiency',
    'input_eff_ELTBiomass_fuel':       'Electrolysis (biomass) fuel efficiency',
    'input_eff_ELTBiogas_fuel':        'Electrolysis (biogas) fuel efficiency',
    'input_eff_ELTIndustry_fuel':      'Electrolysis (industry) fuel efficiency',
    'input_H2storage_trans_cap':       'H2 storage transport capacity (TWh)',
    'input_H2storage_gr3_cap':         'H2 storage group 3 capacity (TWh)',
    'input_H2storage_CHPindv_cap':     'H2 storage individual CHP capacity (TWh)',
    'input_HydrogenImport':            'Hydrogen import (TWh)',
    'input_HydrogenExport':            'Hydrogen export (TWh)',
    'HydrogenImportCost':              'Hydrogen import cost (EUR/GJ)',

    # ── 20. Power-to-X ────────────────────────────────────────────────────────────
    'Input_CO2HydroMaxCapacity':       'CO2 hydrogenation max capacity (MW)',
    'Input_CO2HydroElectrolyserEff':   'CO2 hydrogenation electrolyser efficiency',
    'Input_CO2HydroHydrogenRatio':     'CO2 hydrogenation H2 ratio',
    'Input_CO2HydroSequestrationElecEff': 'CO2 sequestration electric efficiency',
    'Input_CO2HydroSequestrationCO2Eff': 'CO2 sequestration CO2 efficiency',
    'Input_CO2HydroLiqFuel':           'CO2 hydrogenation liquid fuel output (TWh)',
    'Input_SynHydro_HydrogenShare':    'Synthetic hydro H2 share',
    'Input_SynHydro_eff':              'Synthetic hydro efficiency',
    'Input_SynHydro_MaxCapacity':      'Synthetic hydro max capacity (MW)',
    'Input_SynMethan_HydrogenShare':   'Synthetic methane H2 share',
    'Input_SynMethan_eff':             'Synthetic methane efficiency',
    'Input_SynMethan_MaxCapacity':     'Synthetic methane max capacity (MW)',
    'Input_SynDiesel':                 'Synthetic diesel demand (TWh)',
    'Input_SynDiesel_eff':             'Synthetic diesel efficiency',
    'Input_SynJP':                     'Synthetic jet fuel demand (TWh)',
    'Input_SynJP_eff':                 'Synthetic jet fuel efficiency',
    'Input_SynPetrol':                 'Synthetic petrol demand (TWh)',
    'Input_SynPetrol_eff':             'Synthetic petrol efficiency',
    'Input_LiqHydroLiqFuel':           'Liquid hydrogen liquid fuel output (TWh)',
    'Input_LiqHydro_HydrogenShare':    'Liquid hydrogen H2 share',
    'Input_LiqHydro_eff':              'Liquid hydrogen efficiency',

    # ── 21. Ammonia ───────────────────────────────────────────────────────────────
    'Input_NH3Output':                 'Ammonia output (TWh)',
    'Input_NH3_input':                 'Ammonia input (TWh)',
    'Input_N2NH3Eff':                  'N2 to NH3 efficiency',
    'Input_H2NH3Eff':                  'H2 to NH3 efficiency',
    'Input_ElecN2Eff':                 'Electric N2 separation efficiency',
    'Input_NH3MaxCap':                 'Ammonia max capacity (MW)',
    'Input_NH3EltEff_fuel':            'Ammonia electrolysis fuel efficiency',

    # ── 22. Gas system ────────────────────────────────────────────────────────────
    'input_Biogas_prod':               'Biogas production (TWh)',
    'input_Biogas_elec':               'Biogas electricity share',
    'input_Biogas_dh1':                'Biogas DH group 1 share',
    'input_Biogas_dh2':                'Biogas DH group 2 share',
    'input_Biogas_dh3':                'Biogas DH group 3 share',
    'Input_BiogasWetBiomassInput':     'Biogas wet biomass input (TWh)',
    'Input_BiogasSolidBiomassInput':   'Biogas solid biomass input (TWh)',
    'Input_BiogasUpgradeEff':          'Biogas upgrade efficiency',
    'Input_GasiBiomassInput':          'Gasification biomass input (TWh)',
    'Input_GasiElecShare':             'Gasification electricity share',
    'Input_GasiDH3Share':              'Gasification DH group 3 share',
    'Input_GasiColdgasEff':            'Gasification cold gas efficiency',
    'Input_GasiUpgradeEff':            'Gasification upgrade efficiency',
    'Input_GasiCapInput':              'Gasification capacity input (MW)',
    'Input_GasNetStorage':             'Gas network storage (GWh)',

    # ── 23. Biomass conversion ────────────────────────────────────────────────────
    'input_HTL_biomass':               'HTL biomass input (TWh)',
    'input_HTL_eff_H2':                'HTL H2 efficiency',
    'input_HTL_eff_JP':                'HTL jet fuel efficiency',
    'input_HTL_eff_BioDiesel':         'HTL biodiesel efficiency',
    'input_HTL_eff_Methanol':          'HTL methanol efficiency',
    'input_HTL_eff_Syngas':            'HTL syngas efficiency',
    'input_HTL_eff_DHGr3':             'HTL DH group 3 heat efficiency',
    'input_Pyrolysis_Biomass':         'Pyrolysis biomass input (TWh)',
    'input_Pyrolysis_eff_Syngas':      'Pyrolysis syngas efficiency',
    'input_Pyrolysis_eff_BioDiesel':   'Pyrolysis biodiesel efficiency',
    'input_Pyrolysis_eff_JP':          'Pyrolysis jet fuel efficiency',
    'input_Pyrolysis_eff_BioChar':     'Pyrolysis biochar efficiency',
    'input_Pyrolysis_eff_BiocharToCO2': 'Pyrolysis biochar CO2 factor',
    'input_RSC_Biomass':               'RSC biomass input (TWh)',
    'input_RSC_eff_fuel_M1':           'RSC fuel efficiency mode 1',
    'input_RSC_eff_elec_M1':           'RSC electric efficiency mode 1',
    'input_RSC_eff_th_M1':             'RSC thermal efficiency mode 1',
    'input_RSC_eff_fuel_M2':           'RSC fuel efficiency mode 2',
    'input_RSC_eff_elec_M2':           'RSC electric efficiency mode 2',
    'input_RSC_eff_th_M2':             'RSC thermal efficiency mode 2',

    # ── 24. Transport ─────────────────────────────────────────────────────────────
    'input_transport_TWh':             'Transport fuel demand (TWh)',
    'input_transport_TWh_V2G':         'V2G transport demand (TWh)',
    'input_km_diesel':                 'Diesel vehicle efficiency (km/kWh)',
    'input_km_ngas':                   'Natural gas vehicle efficiency (km/kWh)',
    'input_km_biomass':                'Biomass vehicle efficiency (km/kWh)',
    'input_km_h2':                     'Hydrogen vehicle efficiency (km/kWh)',
    'input_km_ev':                     'Electric vehicle efficiency (km/kWh)',
    'input_km_v2g':                    'V2G vehicle efficiency (km/kWh)',
    'input_km_petrol':                 'Petrol vehicle efficiency (km/kWh)',
    'input_km_waste':                  'Waste vehicle efficiency (km/kWh)',
    'Input_km_NH3':                    'Ammonia vehicle efficiency (km/kWh)',

    # ── 25. V2G ───────────────────────────────────────────────────────────────────
    'input_V2G_MaxShare':              'V2G max share of EV fleet',
    'input_V2G_Cap_Charge':            'V2G charging capacity (MW)',
    'input_V2G_Cap_Inv':               'V2G inverter capacity (MW)',
    'input_V2G_ConnectionShare':       'V2G connection share',
    'input_V2G_Eff_Charge':            'V2G charging efficiency',
    'input_V2G_Eff_Inv':               'V2G inverter efficiency',
    'input_V2G_Battery':               'V2G battery storage (GWh)',
    'Input_V2GRegulation':             'V2G regulation mode',
    'Input_V2G_TechnicalRegulation':   'V2G technical regulation mode',
    'Input_V2G_Hydro_Priotization':    'V2G vs hydro prioritisation',
    'input_stabilisation_share_V2G':   'V2G grid stabilisation share',

    # ── 26. Household heating ─────────────────────────────────────────────────────
    'input_HH_HP_heat':                'HH heat pump heat supply (TWh)',
    'input_HH_HP_COP':                 'HH heat pump COP',
    'input_HH_HP_CapLimit':            'HH heat pump capacity limit',
    'input_HH_HP_storage':             'HH heat pump storage (GWh)',
    'input_HH_HP_StorageMaxCapLimit':  'HH heat pump storage max cap limit',
    'input_HH_HP_StorageMinCapLimit':  'HH heat pump storage min cap limit',
    'input_HH_HP_solar':               'HH heat pump solar share',
    'input_HH_EB_heat':                'HH electric boiler heat supply (TWh)',
    'input_HH_EB_CapLimit':            'HH electric boiler capacity limit',
    'input_HH_EB_storage':             'HH electric boiler storage (GWh)',
    'input_HH_coalboiler_eff':         'HH coal boiler efficiency',
    'input_HH_oilboiler_eff':          'HH oil boiler efficiency',
    'input_HH_ngasboiler_eff':         'HH natural gas boiler efficiency',
    'input_HH_bioboiler_eff':          'HH biomass boiler efficiency',
    'input_HH_H2CHP_eff_el':          'HH H2 CHP electric efficiency',
    'input_HH_H2CHP_eff_th':          'HH H2 CHP thermal efficiency',
    'input_HH_H2CHP_heat':            'HH H2 CHP heat supply (TWh)',
    'input_HH_NgasCHP_eff_el':        'HH natural gas CHP electric efficiency',
    'input_HH_NgasCHP_eff_th':        'HH natural gas CHP thermal efficiency',
    'input_HH_NgasCHP_heat':          'HH natural gas CHP heat supply (TWh)',
    'input_HH_BioCHP_eff_el':         'HH biomass CHP electric efficiency',
    'input_HH_BioCHP_eff_th':         'HH biomass CHP thermal efficiency',
    'input_HH_BioCHP_heat':           'HH biomass CHP heat supply (TWh)',

    # ── 27. Cooling ───────────────────────────────────────────────────────────────
    'Input_Cooling_el_demand':         'Cooling electricity demand (TWh)',
    'Input_Cooling_el_eff':            'Cooling electricity efficiency (COP)',
    'Input_Cooling_DHgr1_Heatdemand':  'Cooling DH group 1 heat demand (TWh)',
    'Input_Cooling_DHgr2_Heatdemand':  'Cooling DH group 2 heat demand (TWh)',
    'Input_Cooling_DHgr3_Heatdemand':  'Cooling DH group 3 heat demand (TWh)',
    'Input_Cooling_DHgr1_eff':         'Cooling DH group 1 COP',
    'Input_Cooling_DHgr2_eff':         'Cooling DH group 2 COP',
    'Input_Cooling_DHgr3_eff':         'Cooling DH group 3 COP',
    'input_Cooling_Chillers_demand':   'Cooling chillers demand (TWh)',
    'input_CoolingChillers_eff':       'Cooling chillers efficiency',
    'input_NaturalCooling_Chillers':   'Natural cooling chillers (TWh)',
    'Input_NaturalCooling_DHgr1':      'Natural cooling DH group 1 (TWh)',
    'Input_NaturalCooling_DHgr2':      'Natural cooling DH group 2 (TWh)',
    'Input_NaturalCooling_DHgr3':      'Natural cooling DH group 3 (TWh)',

    # ── 28. Water & desalination ──────────────────────────────────────────────────
    'FreshWaterDemand':                'Fresh water demand (Mm³)',
    'input_FreshWaterStorageCapacity': 'Fresh water storage capacity (Mm³)',
    'input_DesalinationPlantCapacity': 'Desalination plant capacity (m³/h)',
    'input_DesalinationPlantEfficiency': 'Desalination efficiency (kWh/m³)',

    # ── 29. CCS ───────────────────────────────────────────────────────────────────
    'input_CO2_CCS':                   'CCS CO2 capture (Mt)',
    'Input_CCS_Capacity':              'CCS capacity (MW)',
    'input_CCS_El_PerUnit':            'CCS electricity per unit',
    'input_CCS_Regulation_number':     'CCS regulation mode',

    # ── 30. Market & regulation ───────────────────────────────────────────────────
    'input_max_imp_exp':               'Max electricity import/export (MW)',
    'input_nordpool_add_fac':          'Nordpool additive price factor',
    'input_nordpool_mult_fac':         'Nordpool multiplicative price factor',
    'input_depend_fac':                'Electricity price dependency factor',
    'input_import_bottleneck_addprice_factor': 'Import bottleneck price factor',
    'input_exp_pp_reg_fac':            'PP export regulation factor',
    'input_exp_chp_reg_fac':           'CHP export regulation factor',
    'input_exp_hp_reg_fac':            'HP export regulation factor',
    'input_imp_reg_fac':               'Import regulation factor',
    'input_lost_value':                'Lost load value (EUR/MWh)',
    'input_stabilisation_share_min':   'Minimum grid stabilisation share',
    'input_stabilisation_share_chp2':  'CHP group 2 grid stabilisation share',
    'MaxElectricityMarketPrice':       'Maximum electricity market price (EUR/MWh)',
    'MinElectricityMarketPrice':       'Minimum electricity market price (EUR/MWh)',
    'Input_RESZeroOrNegativePrices':   'RES behaviour at zero/negative prices',
    'Input_transys':                   'Transmission system mode',
    'CHP_gridstab_priority':           'CHP grid stabilisation priority',

    # ── 31. Fuel types (indices) ──────────────────────────────────────────────────
    # [1]=Coal [2]=Oil [3]=Natural gas [4]=Biomass [5]=Jet fuel [6]=Biogas
    # [7]=Bio-oil [8]=Waste [9]=Various [10]=Biodiesel [11]=BioCH4 [12]=H2
    'input_fuel_price[1]':             'Coal price (EUR/GJ)',
    'input_fuel_price[2]':             'Oil price (EUR/GJ)',
    'input_fuel_price[3]':             'Natural gas price (EUR/GJ)',
    'input_fuel_price[4]':             'Biomass price (EUR/GJ)',
    'input_fuel_price[5]':             'Jet/liquid fuel price (EUR/GJ)',
    'input_fuel_price[6]':             'Biogas price (EUR/GJ)',
    'input_fuel_price[7]':             'Bio-oil price (EUR/GJ)',
    'input_fuel_price[8]':             'Waste price (EUR/GJ)',
    'input_fuel_price[9]':             'Various fuel price (EUR/GJ)',
    'input_fuel_price[10]':            'Biodiesel price (EUR/GJ)',
    'input_fuel_price[11]':            'Biomethane price (EUR/GJ)',
    'input_fuel_price[12]':            'Hydrogen price (EUR/GJ)',
    'input_fuel_CO2[1]':               'Coal CO2 factor (g/MJ)',
    'input_fuel_CO2[2]':               'Oil CO2 factor (g/MJ)',
    'input_fuel_CO2[3]':               'Natural gas CO2 factor (g/MJ)',
    'input_fuel_CO2[8]':               'Waste CO2 factor (g/MJ)',
    'input_fuel_CO2[9]':               'Various fuel CO2 factor (g/MJ)',

    # ── 32. Variable costs ────────────────────────────────────────────────────────
    'input_VC_boiler_dh':              'Boiler DH variable cost (EUR/MWh)',
    'input_VC_chp_dh':                 'CHP DH variable cost (EUR/MWh)',
    'input_VC_hp_dh':                  'HP DH variable cost (EUR/MWh)',
    'input_VC_pp':                     'Power plant variable cost (EUR/MWh)',
    'input_VC_hydro':                  'Hydro variable cost (EUR/MWh)',
    'Input_VC_eh_dh':                  'Electric heating DH variable cost (EUR/MWh)',
    'input_VC_geothermal':             'Geothermal variable cost (EUR/MWh)',
    'input_VC_electrolyser':           'Electrolyser variable cost (EUR/MWh)',
    'input_VC_pump':                   'Pump variable cost (EUR/MWh)',
    'input_VC_turbine':                'Turbine variable cost (EUR/MWh)',
    'input_VC_V2G':                    'V2G variable cost (EUR/MWh)',
    'input_VC_HydroPump':              'Hydro pump variable cost (EUR/MWh)',
    'input_VC_RSC_M1':                 'RSC variable cost mode 1 (EUR/MWh)',
    'input_VC_RSC_M2':                 'RSC variable cost mode 2 (EUR/MWh)',

    # ── 33. Investment costs by technology ────────────────────────────────────────
    'input_Inv_Wind':                  'Onshore wind investment (MEUR/MW)',
    'input_Period_Wind':               'Onshore wind lifetime (years)',
    'input_FOM_Wind':                  'Onshore wind fixed O&M (% inv)',
    'input_Inv_WindOffshore':          'Offshore wind investment (MEUR/MW)',
    'input_Period_WindOffshore':       'Offshore wind lifetime (years)',
    'input_FOM_WindOffshore':          'Offshore wind fixed O&M (% inv)',
    'input_Inv_PV':                    'Solar PV investment (MEUR/MW)',
    'input_Period_PV':                 'Solar PV lifetime (years)',
    'input_FOM_PV':                    'Solar PV fixed O&M (% inv)',
    'input_Inv_Wave':                  'Wave investment (MEUR/MW)',
    'input_Period_Wave':               'Wave lifetime (years)',
    'input_FOM_Wave':                  'Wave fixed O&M (% inv)',
    'Input_inv_Tidal':                 'Tidal investment (MEUR/MW)',
    'Input_FOM_Tidal':                 'Tidal fixed O&M (% inv)',
    'Input_Period_Tidal':              'Tidal lifetime (years)',
    'Input_inv_CSP':                   'CSP investment (MEUR/MW)',
    'Input_FOM_CSP':                   'CSP fixed O&M (% inv)',
    'Input_Period_CSP':                'CSP lifetime (years)',
    'input_Inv_Nuclear':               'Nuclear investment (MEUR/MW)',
    'input_Period_Nuclear':            'Nuclear lifetime (years)',
    'input_FOM_Nuclear':               'Nuclear fixed O&M (% inv)',
    'input_Inv_Geothermal':            'Geothermal investment (MEUR/MW)',
    'input_Period_Geothermal':         'Geothermal lifetime (years)',
    'input_FOM_Geothermal':            'Geothermal fixed O&M (% inv)',
    'input_Inv_CHP2':                  'CHP group 2 investment (MEUR/MW)',
    'input_Period_CHP2':               'CHP group 2 lifetime (years)',
    'input_Inv_HP2':                   'HP group 2 investment (MEUR/MW)',
    'input_Period_HP2':                'HP group 2 lifetime (years)',
    'input_Inv_Heatstorage2':          'Thermal storage group 2 investment (MEUR/GWh)',
    'input_Period_Heatstorage2':       'Thermal storage group 2 lifetime (years)',
    'input_Inv_CHP3':                  'CHP group 3 investment (MEUR/MW)',
    'input_Period_CHP3':               'CHP group 3 lifetime (years)',
    'input_Inv_HP3':                   'HP group 3 investment (MEUR/MW)',
    'input_Period_HP3':                'HP group 3 lifetime (years)',
    'input_Inv_Heatstorage3':          'Thermal storage group 3 investment (MEUR/GWh)',
    'input_Period_Heatstorage3':       'Thermal storage group 3 lifetime (years)',
    'input_Inv_Boilers_dh':            'DH boiler investment (MEUR/MW)',
    'input_Period_Boilers_dh':         'DH boiler lifetime (years)',
    'input_FOM_Boilers_dh':            'DH boiler fixed O&M (% inv)',
    'input_Inv_PP':                    'Power plant investment (MEUR/MW)',
    'input_Period_PP':                 'Power plant lifetime (years)',
    'input_FOM_PP':                    'Power plant fixed O&M (% inv)',
    'input_Inv_Electrolyser':          'Electrolyser investment (MEUR/MW)',
    'input_Period_Electrolyser':       'Electrolyser lifetime (years)',
    'input_FOM_Electrolyser':          'Electrolyser fixed O&M (% inv)',
    'input_Inv_HydrogenStorage':       'Hydrogen storage investment (MEUR/GWh)',
    'input_Period_HydrogenStorage':    'Hydrogen storage lifetime (years)',
    'input_FOM_HydrogenStorage':       'Hydrogen storage fixed O&M (% inv)',
    'input_Inv_PumpStorage':           'Pump storage investment (MEUR/MW)',
    'input_Period_PumpStorage':        'Pump storage lifetime (years)',
    'input_FOM_PumpStorage':           'Pump storage fixed O&M (% inv)',
    'input_Inv_Pump':                  'Pump investment (MEUR/MW)',
    'input_Period_Pump':               'Pump lifetime (years)',
    'input_FOM_Pump':                  'Pump fixed O&M (% inv)',
    'input_Inv_Turbine':               'Turbine investment (MEUR/MW)',
    'input_Period_Turbine':            'Turbine lifetime (years)',
    'input_FOM_Turbine':               'Turbine fixed O&M (% inv)',
    'input_Inv_solar_dh':              'Solar heat DH investment (MEUR/MW)',
    'input_Period_solar_dh':           'Solar heat DH lifetime (years)',
    'input_FOM_solar_dh':              'Solar heat DH fixed O&M (% inv)',
    'input_Inv_solar_indv':            'Solar heat individual investment (MEUR/MW)',
    'input_Period_solar_indv':         'Solar heat individual lifetime (years)',
    'input_FOM_solar_indv':            'Solar heat individual fixed O&M (% inv)',
    'input_Inv_Boilers_indv':          'Individual boiler investment (MEUR/MW)',
    'input_Period_Boilers_indv':       'Individual boiler lifetime (years)',
    'input_FOM_Boilers_indv':          'Individual boiler fixed O&M (% inv)',
    'input_Inv_HP_indv':               'Individual HP investment (MEUR/MW)',
    'input_Period_HP_indv':            'Individual HP lifetime (years)',
    'input_FOM_HP_indv':               'Individual HP fixed O&M (% inv)',
    'input_Inv_EB_indv':               'Individual electric boiler investment (MEUR/MW)',
    'input_Period_EB_indv':            'Individual electric boiler lifetime (years)',
    'input_FOM_EB_indv':               'Individual electric boiler fixed O&M (% inv)',
    'input_Inv_HydroPower':            'Hydro power investment (MEUR/MW)',
    'input_Period_HydroPower':         'Hydro power lifetime (years)',
    'input_FOM_HydroPower':            'Hydro power fixed O&M (% inv)',
    'input_Inv_HydroStorage':          'Hydro storage investment (MEUR/GWh)',
    'input_Period_HydroStorage':       'Hydro storage lifetime (years)',
    'input_FOM_HydroStorage':          'Hydro storage fixed O&M (% inv)',
    'input_Inv_HydroPump':             'Hydro pump investment (MEUR/MW)',
    'input_Period_HydroPump':          'Hydro pump lifetime (years)',
    'input_FOM_HydroPump':             'Hydro pump fixed O&M (% inv)',
    'input_Inv_Biogas':                'Biogas investment (MEUR/MW)',
    'input_Period_Biogas':             'Biogas lifetime (years)',
    'input_FOM_Biogas':                'Biogas fixed O&M (% inv)',
    'input_Inv_Gasi':                  'Gasification investment (MEUR/MW)',
    'input_Period_Gasi':               'Gasification lifetime (years)',
    'input_FOM_Gasi':                  'Gasification fixed O&M (% inv)',
    'Input_inv_CO2Hydro':              'CO2 hydrogenation investment (MEUR/MW)',
    'Input_FOM_CO2Hydro':              'CO2 hydrogenation fixed O&M (% inv)',
    'Input_Period_CO2Hydro':           'CO2 hydrogenation lifetime (years)',
    'Input_inv_SynFuel':               'Synthetic fuel investment (MEUR/MW)',
    'Input_FOM_SynFuel':               'Synthetic fuel fixed O&M (% inv)',
    'Input_Period_SynFuel':            'Synthetic fuel lifetime (years)',
    'Input_Inv_NH3':                   'Ammonia investment (MEUR/MW)',
    'Input_Period_NH3':                'Ammonia lifetime (years)',
    'Input_FOM_NH3':                   'Ammonia fixed O&M (% inv)',
    'Input_inv_Interconnection':       'Interconnection investment (MEUR/MW)',
    'Input_FOM_Interconnection':       'Interconnection fixed O&M (% inv)',
    'Input_Period_Interconnection':    'Interconnection lifetime (years)',
    'input_Inv_Various1':              'Various 1 investment (MEUR)',
    'input_Period_Various1':           'Various 1 lifetime (years)',
    'input_FOM_Various1':              'Various 1 fixed O&M (% inv)',
    'input_Inv_Various2':              'Various 2 investment (MEUR)',
    'input_Period_Various2':           'Various 2 lifetime (years)',
    'input_FOM_Various2':              'Various 2 fixed O&M (% inv)',
    'input_Inv_Various3':              'Various 3 investment (MEUR)',
    'input_Period_Various3':           'Various 3 lifetime (years)',
    'input_FOM_Various3':              'Various 3 fixed O&M (% inv)',

    # ── 34. Transport investments ─────────────────────────────────────────────────
    'Input_Inv_transport_electric_cars':      'Electric cars investment (MEUR/vehicle)',
    'Input_Period_transport_electric_cars':   'Electric cars lifetime (years)',
    'Input_FOM_transport_electric_cars':      'Electric cars fixed O&M (% inv)',
    'Input_Inv_transport_conventional_cars':  'Conventional cars investment (MEUR/vehicle)',
    'Input_Inv_transport_electric_busses':    'Electric buses investment (MEUR/vehicle)',
    'Input_Inv_transport_diesel_busses':      'Diesel buses investment (MEUR/vehicle)',
    'Input_Inv_transport_electric_trucks':    'Electric trucks investment (MEUR/vehicle)',
    'Input_Inv_transport_diesel_trucks':      'Diesel trucks investment (MEUR/vehicle)',
    'Input_Inv_transport_motorbikes':         'Motorbikes investment (MEUR/vehicle)',

    # ── 35. Notes / metadata ──────────────────────────────────────────────────────
    'notes_model_areaText':            'Model area',
    'notes_model_yearText':            'Model year',
    'notes_developed_yearText':        'Year developed',
    'general_notesText':               'General notes',
}